language: go
env:
  secure: "UGF3ri1lRaTrgDyb+ab7SLOOummH6ryz4EaY5uK2DFVOXrFbupYVFWyBP1km2kCl1yv8pCbiIgIh67CMA6Axu+1j4J3RyPmhJoYVKx7q7BnFrtWgn4tcaJpscmWdxT+UEbmcOg/jp2annM4o52yjlSDf3rs6KTo1wsF6Syr9+CICzOet7f08+bZ2lTxf918BmVtkQ3IRSx2brJSGvOQthC328lSOB6+B3L8kVW5zTjDvJuxW+RY7n3F9rO9Ur4jXeis+Woyx2ORHkfvH/uO6gGx0SjJ9MkaW63kzR3zzHaY8eO+oT1vMQMmJJqTzRHJ9flEzMIBexayDSXwrI9ccYS6jd82/y98nZRJvydjnj/nZQW50FPvjaPxdsWL2LrKcQ7GhpHVNliwsjDfSzgAK/4kIS5Rys1qfOolBvst2DyPkyqItla4R7XMv5AikDcHEK2UlzOUIRcb+MJMsKKhLm18kEtLQvnZMRANM1KYLe/kWboS6AdSnNu9YkucVF/BYWBo+d/lLqtiT0YexQd8VCnqOT/NeHKAz30LWa65MFZb9PSmv8RRziWZ4BleRvvF9OP+tkKMBqbb+7k13b6m3ex9t2HcpGav1vxwLMd5gkpuUmwFYbD/hS/0otg05X7jOcudlLgG0eSDZBQwpDE0I/b/EavH/vyybvblU6OlSieQ="
install: go install github.com/DATA-DOG/godog/cmd/godog
script:
- go test
- godog
